=== webmaster442/BookGen/Schema/config.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Config",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "TOCFile": {
      "type": "string"
    },
    "ImageDir": {
      "type": "string"
    },
    "ScriptsDirectory": {
      "type": "string"
    },
    "HostName": {
      "type": "string"
    },
    "Index": {
      "type": "string"
    },
    "Version": {
      "type": "integer",
      "format": "int32"
    },
    "LinksOutSideOfHostOpenNewTab": {
      "type": "boolean"
    },
    "Metadata": {
      "$ref": "#/definitions/Metadata"
    },
    "TargetWeb": {
      "$ref": "#/definitions/BuildConfig"
    },
    "TargetPrint": {
      "$ref": "#/definitions/BuildConfig"
    },
    "TargetEpub": {
      "$ref": "#/definitions/BuildConfig"
    },
    "TargetWordpress": {
      "$ref": "#/definitions/BuildConfig"
    },
    "TargetPostProcess": {
      "$ref": "#/definitions/BuildConfig"
    },
    "Translations": {
      "$ref": "#/definitions/Translations"
    },
    "BookLanguage": {
      "type": "string"
    }
  },
  "definitions": {
    "Metadata": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Author": {
          "type": "string"
        },
        "CoverImage": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    },
    "BuildConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "OutPutDirectory": {
          "type": "string"
        },
        "TemplateFile": {
          "type": "string"
        },
        "TemplateAssets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Asset"
          }
        },
        "StyleClasses": {
          "$ref": "#/definitions/StyleClasses"
        },
        "TemplateOptions": {
          "$ref": "#/definitions/TemplateOptions"
        },
        "ImageOptions": {
          "$ref": "#/definitions/ImageOptions"
        }
      }
    },
    "Asset": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Source": {
          "type": "string"
        },
        "Target": {
          "type": "string"
        }
      }
    },
    "StyleClasses": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Heading1": {
          "type": "string"
        },
        "Heading2": {
          "type": "string"
        },
        "Heading3": {
          "type": "string"
        },
        "Image": {
          "type": "string"
        },
        "Table": {
          "type": "string"
        },
        "Blockquote": {
          "type": "string"
        },
        "Figure": {
          "type": "string"
        },
        "FigureCaption": {
          "type": "string"
        },
        "Link": {
          "type": "string"
        },
        "OrderedList": {
          "type": "string"
        },
        "UnorederedList": {
          "type": "string"
        },
        "ListItem": {
          "type": "string"
        }
      }
    },
    "TemplateOptions": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "ImageOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "RecodeJpegToWebp": {
          "type": "boolean"
        },
        "EnableResize": {
          "type": "boolean"
        },
        "MaxWidth": {
          "type": "integer",
          "format": "int32"
        },
        "MaxHeight": {
          "type": "integer",
          "format": "int32"
        },
        "InlineImageSizeLimit": {
          "type": "integer",
          "format": "int64"
        },
        "ImageQuality": {
          "type": "integer",
          "format": "int32"
        },
        "RecodePngToWebp": {
          "type": "boolean"
        },
        "EncodeSvgAsWebp": {
          "type": "boolean"
        }
      }
    },
    "Translations": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== webmaster442/BookGen/Test/BookGen.TestsSystem/Book/.bookgen/bookgen.json
{
  "$schema": "https://raw.githubusercontent.com/webmaster442/BookGen/master/Schema/config.schema.json",
  "TOCFile": "Summary.md",
  "ImageDir": "Img",
  "ScriptsDirectory": "",
  "HostName": "http://localhost:8080/",
  "Index": "Index.md",
  "Version": 1014,
  "LinksOutSideOfHostOpenNewTab": true,
  "Metadata": {
    "Author": "Test author",
    "CoverImage": "Img/test.png",
    "Title": "Test book"
  },
  "TargetWeb": {
    "OutPutDirectory": "output/web",
    "TemplateFile": "",
    "TemplateAssets": [
      {
        "Source": "",
        "Target": ""
      }
    ],
    "StyleClasses": {
      "Heading1": "",
      "Heading2": "",
      "Heading3": "",
      "Image": "img-fluid mx-auto rounded",
      "Table": "table",
      "Blockquote": "blockquote",
      "Figure": "figure",
      "FigureCaption": "figure-caption",
      "Link": "",
      "OrderedList": "",
      "UnorederedList": "",
      "ListItem": ""
    },
    "TemplateOptions": {
      "CookieDisplayBannerEnabled": "true"
    },
    "ImageOptions": {
      "RecodeJpegToWebp": false,
      "EnableResize": true,
      "MaxWidth": 1080,
      "MaxHeight": 1080,
      "InlineImageSizeLimit": 65536,
      "ImageQuality": 95,
      "RecodePngToWebp": false,
      "EncodeSvgAsWebp": false
    }
  },
  "TargetPrint": {
    "OutPutDirectory": "output/print",
    "TemplateFile": "",
    "TemplateAssets": [
      {
        "Source": "",
        "Target": ""
      }
    ],
    "StyleClasses": {
      "Heading1": "",
      "Heading2": "",
      "Heading3": "",
      "Image": "",
      "Table": "",
      "Blockquote": "",
      "Figure": "",
      "FigureCaption": "",
      "Link": "",
      "OrderedList": "",
      "UnorederedList": "",
      "ListItem": ""
    },
    "TemplateOptions": {
      "CookieDisplayBannerEnabled": "true"
    },
    "ImageOptions": {
      "RecodeJpegToWebp": false,
      "EnableResize": true,
      "MaxWidth": 1080,
      "MaxHeight": 1080,
      "InlineImageSizeLimit": 0,
      "ImageQuality": 95,
      "RecodePngToWebp": false,
      "EncodeSvgAsWebp": false
    }
  },
  "TargetEpub": {
    "OutPutDirectory": "output/epub",
    "TemplateFile": "",
    "TemplateAssets": [
      {
        "Source": "",
        "Target": ""
      }
    ],
    "StyleClasses": {
      "Heading1": "",
      "Heading2": "",
      "Heading3": "",
      "Image": "",
      "Table": "",
      "Blockquote": "",
      "Figure": "",
      "FigureCaption": "",
      "Link": "",
      "OrderedList": "",
      "UnorederedList": "",
      "ListItem": ""
    },
    "TemplateOptions": {
      "CookieDisplayBannerEnabled": "true"
    },
    "ImageOptions": {
      "RecodeJpegToWebp": false,
      "EnableResize": true,
      "MaxWidth": 1080,
      "MaxHeight": 1080,
      "InlineImageSizeLimit": 9223372036854775807,
      "ImageQuality": 95,
      "RecodePngToWebp": false,
      "EncodeSvgAsWebp": false
    }
  },
  "TargetWordpress": {
    "OutPutDirectory": "output/wordpress",
    "TemplateFile": "",
    "TemplateAssets": [
      {
        "Source": "",
        "Target": ""
      }
    ],
    "StyleClasses": {
      "Heading1": "",
      "Heading2": "",
      "Heading3": "",
      "Image": "",
      "Table": "",
      "Blockquote": "",
      "Figure": "",
      "FigureCaption": "",
      "Link": "",
      "OrderedList": "",
      "UnorederedList": "",
      "ListItem": ""
    },
    "TemplateOptions": {
      "WordpressTargetHost": "https://localhost/",
      "WordpressAuthorDisplayName": "John Doe",
      "WordpressAuthorLastName": "Doe",
      "WordpressAuthorFirstName": "John",
      "WordpressAuthorEmail": "john.doe@provider.com",
      "WordpressAuthorLogin": "wploginuser",
      "WordpressAuthorId": "1",
      "WordpressItemType": "page",
      "WordpresCreateParentTitle": "Parent",
      "WordpressCreateParent": "true",
      "WordpressCreateFillerPages": "true",
      "WordpressCommentStatus": "closed",
      "WordpressSkipPageTitle": "true",
      "WordpressTagCategory": "post_tag"
    },
    "ImageOptions": {
      "RecodeJpegToWebp": false,
      "EnableResize": true,
      "MaxWidth": 1080,
      "MaxHeight": 1080,
      "InlineImageSizeLimit": 9223372036854775807,
      "ImageQuality": 95,
      "RecodePngToWebp": false,
      "EncodeSvgAsWebp": false
    }
  },
  "TargetPostProcess": {
    "OutPutDirectory": "output/postproc",
    "TemplateFile": "",
    "TemplateAssets": [
      {
        "Source": "",
        "Target": ""
      }
    ],
    "StyleClasses": {
      "Heading1": "",
      "Heading2": "",
      "Heading3": "",
      "Image": "",
      "Table": "",
      "Blockquote": "",
      "Figure": "",
      "FigureCaption": "",
      "Link": "",
      "OrderedList": "",
      "UnorederedList": "",
      "ListItem": ""
    },
    "TemplateOptions": {
      "CookieDisplayBannerEnabled": "true"
    },
    "ImageOptions": {
      "RecodeJpegToWebp": false,
      "EnableResize": true,
      "MaxWidth": 1080,
      "MaxHeight": 1080,
      "InlineImageSizeLimit": 9223372036854775807,
      "ImageQuality": 95,
      "RecodePngToWebp": false,
      "EncodeSvgAsWebp": false
    }
  },
  "Translations": {
    "Search_ButtonText": "Search",
    "Search_NoResults": "No Results found",
    "Search_Results": "Results",
    "Search_PageTitle": "Search",
    "Search_TextBoxText": "Type here to search",
    "Cookie_Header": "Do you like Cookies?",
    "Cookie_Description": "This Site uses cookies.",
    "Cookie_Link": "https://cookiesandyou.com/",
    "Cookie_LearnMore": "Learn more",
    "Cookie_Accept": "Okay",
    "Navigate_Next": "Next",
    "Navigate_Previous": "Previous",
    "Navigate_Search": "Search",
    "Navigate_OnThisPage": "On this page",
    "Navigate_Contents": "Contents",
    "Navigate_Top": "Go to top"
  },
  "BookLanguage": "en-US"
}
